# Dash Writeback Application Configuration
# For Databricks Apps Deployment (Optional)
# This configuration allows deploying the app as a Databricks App

command:
- python
- -m
- dash_dbx_writeback.app

env:
# PostgreSQL Database Configuration
- name: POSTGRES_HOST
  value: localhost
- name: POSTGRES_PORT
  value: "5432"
- name: POSTGRES_DATABASE
  value: dash_writeback
- name: POSTGRES_USER
  value: postgres
- name: POSTGRES_PASSWORD
  value: changeme
- name: POSTGRES_SCHEMA
  value: public
- name: POSTGRES_SSL_MODE
  value: prefer

# Application Configuration
- name: DEBUG
  value: "false"
- name: APP_HOST
  value: 0.0.0.0
- name: APP_PORT
  value: "$DATABRICKS_APP_PORT"

# Connection Pool Settings
- name: POSTGRES_POOL_SIZE
  value: "5"
- name: POSTGRES_MAX_OVERFLOW
  value: "10"

