command:
  - python
  - -m
  - src.dash_dbx_writeback

resources:
  - name: sql-warehouse
  - name: postgres-database

env:
  - name: 'DATABRICKS_CATALOG'
    value: 'daveok'
  - name: 'DATABRICKS_SCHEMA'
    value: 'excel_app'
  - name: 'DATABRICKS_WAREHOUSE_ID'
    valueFrom: 'sql-warehouse'
  - name: 'LAKEBASE_SCHEMA'
    value: 'public'