command:
  - python
  - src/app.py

env:
  - name: "WAREHOUSE_HTTP_PATH"
    value: "/sql/1.0/warehouses/6ca1701fb71cf0f5"
  - name: "UNITY_CATALOG_CATALOG"
    value: "big_test"
  - name: "UNITY_CATALOG_SCHEMA"
    value: "default"
  - name: "POSTGRES_HOST"
    value: "instance-63c75c4c-caaa-4051-9a32-cf31a0e6c74e.database.azuredatabricks.net"
  - name: "POSTGRES_DATABASE"
    value: "databricks_postgres"
  - name: "POSTGRES_SCHEMA"
    value: "public"
