command:
  - python
  - src/app.py

env:
  - name: "WAREHOUSE_HTTP_PATH"
    value: "/sql/1.0/warehouses/2a5e79eb445ff34a"
  - name: "UNITY_CATALOG_CATALOG"
    value: "big_test"
  - name: "UNITY_CATALOG_SCHEMA"
    value: "default"
  - name: "POSTGRES_HOST"
    value: "instance-d2f90d65-6a8f-446d-9c9c-b96cd146aa7c.database.azuredatabricks.net"
  - name: "POSTGRES_DATABASE"
    value: "databricks_postgres"
  - name: "POSTGRES_SCHEMA"
    value: "public"
